//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Product_Management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NLog_Error
    {
        public int Id { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public string Level { get; set; }
        public string Host { get; set; }
        public string Type { get; set; }
        public string Logger { get; set; }
        public string Message { get; set; }
        public string stacktrace { get; set; }
    }
}
