//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HSM.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Room
    {
        public int RoomID { get; set; }
        public string RoomName { get; set; }
        public string RoomCategory { get; set; }
        public int RoomPrice { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<int> Room_Id { get; set; }
    
        public virtual Booking Booking { get; set; }
        public virtual HotelM HotelM { get; set; }
    }
}
