//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.DAL.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WebDBEntities : DbContext
    {
        public WebDBEntities()
            : base("name=WebDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Booking_Detail> Booking_Detail { get; set; }
        public virtual DbSet<Hotel_Details> Hotel_Details { get; set; }
        public virtual DbSet<Room_Details> Room_Details { get; set; }
        public virtual DbSet<user_detail> user_detail { get; set; }
    }
}
